### ISSUE TITLE
Make a Login page UI only

### ISSUE THREAD

**Issue by Arafatmollik1** [Arafatmollik1/fundy-tickets-nextjs#2]
Check out code from this PR https://github.com/Arafatmollik1/fundy-tickets-nextjs/pull/10

You can see that a login route has been made.

The easiest way to make any route with nextjs is to make a folder on the name of the route and then make page.jsx under that folder and automatically it will trigger the code that is inside page.jsx when someone enters the route.

So now you should `git pull` the develop branch and make a new branch from it called login-ui.

Use html and tailwind to design page.jsx in login folder.

Make it as similar as possible with the design. 

No, login functionality must be added in this PR. Just UI changes.

Just the inputs, text and button. No interactivity needed.

<img width="302" alt="Screenshot 2024-06-09 at 5 59 53" src="https://github.com/Arafatmollik1/fundy-tickets-nextjs/assets/49017356/c7d5beae-a8f8-49fc-9273-0233a659122e">

**Comment by AR-Aourangazeb-Alif** [comment]
As I don't have Figma pro plan purchased, I can't use the dev mode. Hence I am using an alternative platform. Everything is working fine except the font-family. The font-families of the texts didn't translate well.

**Can you please tell me what font-families you used in the "login" route figma design? **

**Comment by Arafatmollik1** [comment]
@AR-Aourangazeb-Alif 
Please use Roboto as main font.
https://fonts.google.com/specimen/Roboto

and use josefin only for the logo text which is "Fundy"
https://fonts.google.com/specimen/Josefin+Sans

**Comment by Arafatmollik1** [comment]
@AR-Aourangazeb-Alif if you are done with the issue put a PR. if you are not done then it's usually a good idea to commit changes and push the branch. Only when you are done and ready then put a pull request!
